mode: DEV

server:
  port: 4567
  context-path: /shixun/api

auth:
  package: top.oahnus.controller.auth
  admin:
    package: top.oahnus.controller.administrator
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shixun_17_02_26?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/shixun_17_02_26?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: F1203005_5120309188_LuHao
#    driver-class-name: org.mariadb.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  jpa:
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.MySQL5Dialect
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.oahnus.entity
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true

logging:
  level: info


# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.state.descriptor.sql.BasicBinder=TRACE

