mode: DEV

server:
  port: 4567
  context-path: /api

admin:
  package: top.oahnus.controller.administrator
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shixun?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 100
      max-wait: 3000
  jpa:
    database: mysql
    database-platform: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
  cache:
    jcache:
      config: classpath:ehcache.xml
  aop:
    auto: true
  output:
    ansi:
      enabled: always
  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 16MB
logging:
  pattern:
    console: "%clr(%d %-5level %logger : %msg%n)"
  level:
    top.oahnus: debug
    org.hibernate: error
  file: app.log

# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.state.descriptor.sql.BasicBinder=TRACE

