mode: DEV

server:
  port: 4567
  context-path: /shixun/api

auth:
  package: top.oahnus.controller.auth
  admin:
    package: top.oahnus.controller.administrator
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shixun_17_02_26?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 100
      max-wait: 3000
  aop:
    auto: true
  output:
    ansi:
      enabled: always
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.oahnus.entity
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true

logging:
  pattern:
    console: "%clr(%d %-5level %logger : %msg%n)"
  level:
    top.oahnus: debug
  file: app.log


# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.state.descriptor.sql.BasicBinder=TRACE

